### ISSUE TITLE
audio stutters interruptions

### ISSUE THREAD

**Issue by djihad2323** [ThePBone/GalaxyBudsClient#446] opened 2024-02-07 02:33 UTC
I installed the galaxy unofficial app. After uninstalling it, I had crashes and stutters etc. with the standard app. I think there is a problem in the registry.

**Comment by ThePBone** [comment] 2024-02-10 23:12
Duplicate of https://github.com/ThePBone/GalaxyBudsClient/issues/389

These are more likely issues with the Bluetooth drivers if the issues persist after uninstalling.

**Closed by ThePBone** 2024-02-10 23:12 UTC
Labels: bug
