### ISSUE TITLE
[REQ] Add option to increase zoom level

### ISSUE THREAD

**Issue by m44soroush** [ThePBone/GalaxyBudsClient#403] opened 2023-04-12 11:19 UTC
I would like to request a feature for the Linux client of Galaxy Buds that would allow me to adjust the zoom level on my 4k resolution laptop, as the current interface is too small to use comfortably.

**Comment by arbitar** [comment] 2023-08-11 19:28
A workaround, until this issue is correctly resolved:

This project uses Avalonia as its UI library. As per [Avalonia's project wiki](https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI), scale can be adjusted on a per-display level.

I ran `xrandr` to determine the name of my display (mine was eDP-1 for my laptop) then I modified my application launcher's entry for this application to set the following environment variable: `AVALONIA_SCREEN_SCALE_FACTORS='eDP-1=2.5'` - note the two values of importance, `eDP-1` must match the display as seen in `xrandr`, and `2.5`, the scale factor I wanted that brings it to a legible size on my laptop.

The program now launches at a sane scale. If you have other displays, you will need to semicolon separate the `<display ID>=<scale factor>` values in the env var.

**Comment by mich2k** [comment] 2023-10-12 10:03
> A workaround, until this issue is correctly resolved:
> 
> This project uses Avalonia as its UI library. As per [Avalonia's project wiki](https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI), scale can be adjusted on a per-display level.
> 
> I ran `xrandr` to determine the name of my display (mine was eDP-1 for my laptop) then I modified my application launcher's entry for this application to set the following environment variable: `AVALONIA_SCREEN_SCALE_FACTORS='eDP-1=2.5'` - note the two values of importance, `eDP-1` must match the display as seen in `xrandr`, and `2.5`, the scale factor I wanted that brings it to a legible size on my laptop.
> 
> The program now launches at a sane scale. If you have other displays, you will need to semicolon separate the `<display ID>=<scale factor>` values in the env var.

where is the launcher located? I am on a highdpi and the UI is unreadable

**Comment by mich2k** [comment] 2023-10-12 15:23
Plus probably this issue may be a duplicate of #311

**Closed** 2024-02-10 22:05 UTC
Labels: enhancement
