### ISSUE TITLE
[BUG] Connection popup - minimalizing full-screen apps and deselecting other apps

### ISSUE THREAD

**Issue by Joedmin** [ThePBone/GalaxyBudsClient#154] opened 2021-02-16 17:22 UTC
The connection popup minimalizes other fullscreen windows and when a popup appears the popup gets selected.
When you are, for example writing something, in another app the app gets deselected and the popup window gets selected.

Edit:
I'd like to make the widget override the fullscreen app or don't show it when is app in fullscreen mode. And to make it stop deselecting other apps.

**Comment by ThePBone** [comment] 2021-02-16 20:23
Unfortunately, I cannot reproduce any of these issues. The connection popup displays correctly for me when another app is in fullscreen. When writing something in my web browser or Word, the other app does not get deselected/loses focus; I can continue writing like normal:
![screencap](https://user-images.githubusercontent.com/38386967/108117216-e7236e00-709c-11eb-8461-06dd35083037.gif)

Which Windows/Linux version are you using? Does this happen with all applications are just a few ones?

**Comment by Joedmin580** [comment] 2021-02-17 08:49
I have Windows 10 Home edition, version 20H2, 64 bit. I noticed, that it doesn't deselect apps now, weird. But it still minimalizes the full-screen apps, for example, games.

**Comment by Joedmin580** [comment] 2021-02-19 11:20
Sorry to bother you, but it's now deselecting apps, for example, the Mozilla Firefox:
![ezgif-3-10d1c4f4b125](https://user-images.githubusercontent.com/73015399/108498162-c6316780-72ac-11eb-90ab-07561e6edf52.gif)

**Comment by VCTGomes** [comment] 2021-03-09 22:32
How can I turn it on? The pop-up isn't being showed for me

**Comment by VCTGomes** [comment] 2021-03-10 00:57
> @VCTGomes Press the 'Options' button in the top left corner and go to 'Configure connection popup'. You can enable it there.

Ooww tks. I didn't notice it yet. I've turned it on now.

If I could suggest something to the developers, it'd be the pop-up to connect too.

**Comment by ThePBone** [comment] 2024-02-10 22:24
This should be fixed by 20e9c10517344117f2c6861ffead6314769d7f8e and the fix will be included in the next update

**Closed by ThePBone** 2024-02-10 22:24 UTC
Labels: bug
