### ISSUE TITLE
The app only opens from the terminal[BUG] 

### ISSUE THREAD

**Issue by Pouya-cpu** [ThePBone/GalaxyBudsClient#355] opened 2022-08-23 09:47 UTC
**Describe the bug**  
When I click the app from the applications launcher, the app doesn't want to open. but when I write the app name from the terminal, it launches immediately.

**Expected behavior**  
It runs fine when you open it from the terminal, but I expected it to launch from the app launcher.

**Desktop (please complete the following information):**  
 - OS: Arch Linux
 
 - Application version:  4.5.2-3 from the AUR.

**Log files**  
I don't know where the log file is located in arch Linux. if a log file is necessary, let me know how to the log file.

**Comment by Pouya-cpu** [comment] 2022-08-23 09:49
I made an writing mistake on the last line. I meant to say "let me know how to access the log file". Just wanted to clarify.

**Comment by andrescollares** [comment] 2022-08-23 19:41
May be a duplicate of #334.

You should try:
> Changing DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 in /usr/share/applications/galaxybudsclient.desktop resolved the issue.

**Comment by camellan** [comment] 2022-09-20 16:37
If you build the project with the command: "dotnet publish -r linux-x64 -c Release --self-contained" then in the publish folder the program is fully working.

**Comment by ThePBone** [comment] 2024-02-10 23:08
See https://github.com/ThePBone/GalaxyBudsClient/issues/334

**Closed by ThePBone** 2024-02-10 23:08 UTC
Labels: bug
