### ISSUE TITLE
Program crash while doing normal stuff (watching video, ecc...)

### ISSUE THREAD

**Issue by giovanniro98** [ThePBone/GalaxyBudsClient#108] opened 2021-01-23 15:09 UTC
Windows 64bit (last actions version).
I know that you have fixed some crash issues but I still have some.
It happens when I'm watching video and doing normal stuff (no variation on the status of the buds) but I don't know how to debug it.

**Comment by ThePBone** [comment] 2021-01-23 19:35
I noticed that the tray icon would sometimes disappear as well after letting the app run for several hours. However, it does not crash; it just exits normally (which is much harder to debug). There was no crash reported in Windows's Event Viewer, nor in the application log file. 

Upon further inspection, it looks like something triggered an accidental exit of the whole program. This was probably caused by a bug in the underlying UI toolkit that fails to process `OnClosing` events correctly.

Anyways, I've pushed a fix for this (commit c7b28269fba129e12de33415d725ccc16bcd79d3). You can get a new build from the automatic workflows.

Still, I'm not 100% sure whether this was the actual issue or just unrelated.

**Closed by ThePBone** 2021-01-23 19:35 UTC
Labels: crash

**Comment by giovanniro98** [comment] 2021-01-24 20:38
No crash so far in a day of using last build.
