### ISSUE TITLE
[BUG]  Can't find buds 2 old firmware

### ISSUE THREAD

**Issue by filipemonguito** [ThePBone/GalaxyBudsClient#361] opened 2022-08-31 19:04 UTC
I can't find the old firmware for the buds 2. I have clicked the Allow firmware downgrading and I even tried disabling windows firewall. I don't know if it may be related but I'm using windows 11.

**Comment by ThePBone** [comment] 2022-12-13 23:33
Buds2 firmware is backed up, but only visible when using a later API version:  https://fw.timschneeberger.me/v2/firmware/buds2

Maybe there's a bug inside the app that fails to parse the JSON. I'll check when I have time.

**Comment by ThePBone** [comment] 2022-12-14 00:57
Fixed by #376

Precompiled binaries with the fix are available here:
* Windows: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/3690686526
* Linux: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/3690686531

**Closed by ThePBone** 2022-12-14 00:57 UTC
Labels: bug

**Comment by Galunid** [comment] 2022-12-14 01:19
I believe it should also be fine to close #375 as it's most likely related and is already fixed ;)

**Comment by ThePBone** [comment] 2022-12-14 01:26
Yes. That issue was also caused by me not collecting any Buds 2 Pro firmware until now, but I pushed an update for the API to scrape that firmware too.

**Comment by 24fpsDaVinci** [comment] 2022-12-14 22:30
just a heads up, my buds 2 pro went offline and bricked after I uploaded the firmware with the new build. I exchanged them at the store and connecting them to a Samsung device at the store i updated them without issue. No idea what caused the issue in the new build.

**Comment by ThePBone** [comment] 2022-12-14 22:43
Sorry about that. I'm guessing that a firmware for different model was somehow flashed onto the device.

For now, I've removed firmware updates for the Buds 2 Pro from the API until I have more time to take a look at the offending firmware binary.

**Comment by Mocar2D** [comment] 2023-02-10 23:01
@ThePBone hey mind adding the repository to the release version of the app? it is not there afaik
