### ISSUE TITLE
[BUG] Temperature display on MainWindow has the °C cut off

### ISSUE THREAD

**Issue by sidevesh** [ThePBone/GalaxyBudsClient#467] opened 2024-02-20 20:25 UTC
**Describe the bug**  
Temperature display on MainWindow has the °C cut off

**To Reproduce**  
Connect Galaxy Buds
Open the app

**Expected behavior**  
°C should not get cut off

**Screenshots**  
![Screenshot 2024-02-21 at 1 52 40 AM](https://github.com/ThePBone/GalaxyBudsClient/assets/17254413/885dc267-00f0-4d2c-b591-cf4ec5e5d59e)

**Desktop (please complete the following information):**  
 - OS: macOS 14.3.1
 
 - Application version: latest master CI build

**Comment by ThePBone** [comment] 2024-02-20 20:31
This seems to be a regression in Avalonia's nightly build. For me, some text fields are missing altogether after switching back and forth between pages. Some are cut off.

**Comment by ThePBone** [comment] 2024-02-23 19:42
Appears to be fixed by the latest Avalonia nightly version.

**Closed** 2024-02-23 19:42 UTC
Labels: bug
